/** Base oficial GeoBairros CG — Campo Grande-MS (7 regiões, 67 bairros). Fonte: Planurb/SISGRAN. */

/** @type {{ regiao: string, bairro: string, parcelamentos: string[] }[]} */
export const BASE = [
  { regiao: "Anhanduizinho", bairro: "Aero Rancho", parcelamentos: ["Conjunto Habitacional Aero Rancho (Setores de I a VII)", "Dona Júlia", "Vila Ana Maria", "Jardim das Hortênsias", "Parque do Sol (parte)"] },
  { regiao: "Anhanduizinho", bairro: "Alves Pereira", parcelamentos: ["Jardim Alves Pereira", "Santa Maria", "Vila Novo Século", "Jardim Morente", "Residencial Betaville"] },
  { regiao: "Anhanduizinho", bairro: "Centenário", parcelamentos: ["Jardim Centenário", "Iracy Coelho (I, II e III)", "Parque Lageado", "Jardim Santa Emília (parte)"] },
  { regiao: "Anhanduizinho", bairro: "Centro Oeste", parcelamentos: ["Jardim Centro Oeste", "Jardim Colorado", "Jardim Macaúbas", "Parque Novo Século", "Jardim Canguru", "Marajoara"] },
  { regiao: "Anhanduizinho", bairro: "Jacy", parcelamentos: ["Vila Jacy", "Jardim Paulista (parte)", "IPÊ", "Vila Paraíso", "Vila Progresso (parte)"] },
  { regiao: "Anhanduizinho", bairro: "Los Angeles", parcelamentos: ["Jardim Los Angeles", "Jardim Uirapuru", "Vegas", "Parque do Sol", "Jardim Campo Nobre", "Morada do Sol"] },
  { regiao: "Anhanduizinho", bairro: "Parati", parcelamentos: ["Jardim Parati", "Jardim Monte Alegre", "Piratininga (parte)", "Jardim Anápolis", "Residencial Spalding"] },
  { regiao: "Anhanduizinho", bairro: "Pioneiros", parcelamentos: ["Vila Pioneiros", "Jardim Botafogo", "Vila Adelina", "Joana D'Arc", "Vila Divisória"] },
  { regiao: "Anhanduizinho", bairro: "Piratininga", parcelamentos: ["Vila Piratininga", "Jardim Nhanhá", "Promorar", "Vila Ipiranga", "Núcleo Piratininga", "Vila Getúlia Barbosa"] },
  { regiao: "Anhanduizinho", bairro: "Taquarussu", parcelamentos: ["Vila Taquarussu", "Vila Carvalho (parte)", "Jardim Jacy (parte)", "Vila Belo Horizonte"] },
  { regiao: "Anhanduizinho", bairro: "Universitário", parcelamentos: ["Jardim Universitário", "Vila Olinda", "Jardim Dynamic", "Cohab Universitária", "Jardim Continental", "Vila Maciel"] },
  { regiao: "Bandeira", bairro: "Carlota", parcelamentos: ["Jardim Carlota", "Vila Albuquerque (parte)", "Jardim Its", "Vila Santos Dumont", "Mansur"] },
  { regiao: "Bandeira", bairro: "Dr. Albuquerque", parcelamentos: ["Vila Albuquerque", "Três Corações", "Vila Morumbi", "Vila Auxiliadora"] },
  { regiao: "Bandeira", bairro: "Itanhangá (Parte Sul)", parcelamentos: ["Jardim Itanhangá", "Vila Rosa Pires (parte)", "Vila Miguel Couto"] },
  { regiao: "Bandeira", bairro: "Maria Aparecida Pedrossian", parcelamentos: ["Residencial Maria Aparecida Pedrossian", "Jardim Panorama", "Oiti", "Residencial Damha (I, II, III, IV)", "Chácara Cachoeira (parte)"] },
  { regiao: "Bandeira", bairro: "Moreninha", parcelamentos: ["Moreninha I", "Moreninha II", "Moreninha III", "Moreninha IV", "Vila Nova Capital", "Santa Felicidade", "José Maksoud"] },
  { regiao: "Bandeira", bairro: "Rita Vieira", parcelamentos: ["Jardim Rita Vieira (I, II e III)", "Parque Dallas", "Vila Morumbi (parte)", "Jardim das Mansões"] },
  { regiao: "Bandeira", bairro: "São Lourenço", parcelamentos: ["Jardim São Lourenço", "Vila Vilasboas (parte)", "Tiradentes (parte)", "Jardim Auxiliadora"] },
  { regiao: "Bandeira", bairro: "Tiradentes", parcelamentos: ["Jardim Tiradentes", "Residencial Dahma (fração)", "Jardim Vitória", "Parque dos Esbórnias", "Assaf Trad"] },
  { regiao: "Bandeira", bairro: "Tv Morena", parcelamentos: ["Jardim Paulista", "Vila Santa Dorotheia", "Vila Albuquerque (parte)"] },
  { regiao: "Bandeira", bairro: "Vilasboas", parcelamentos: ["Jardim Vilasboas", "Jardim Bela Vista (parte)", "Novo Horizonte", "Vila Marques"] },
  { regiao: "Centro", bairro: "Amambai", parcelamentos: ["Vila Amambai", "Vila Bandeirantes (parte)", "Cabeça de Boi", "Vila Militar"] },
  { regiao: "Centro", bairro: "Cabreúva", parcelamentos: ["Vila Cabreúva", "Orla Ferroviária (parte)", "Vila Estilo"] },
  { regiao: "Centro", bairro: "Centro", parcelamentos: ["Planta Original de Campo Grande", "Vila Cidade", "Rui Barbosa"] },
  { regiao: "Centro", bairro: "Cruzeiro", parcelamentos: ["Vila Cruzeiro", "Jardim Autonomista (parte)", "Vila Santa Marta", "Vila Sônia"] },
  { regiao: "Centro", bairro: "Glória", parcelamentos: ["Vila Glória", "Itaimbé", "Vila Miguel Couto (parte)", "Vila Erica"] },
  { regiao: "Centro", bairro: "Jardim dos Estados", parcelamentos: ["Jardim dos Estados", "Vila Santa Odete", "Vila Guaraciaba", "Vila Tupaceretan", "Vila Esportiva", "Jardim Aclimação"] },
  { regiao: "Centro", bairro: "Monte Líbano", parcelamentos: ["Jardim Monte Líbano", "Vila São Jorge da Lagoa (parte)", "Vila Kellen"] },
  { regiao: "Centro", bairro: "Planalto", parcelamentos: ["Vila Planalto", "Vila Militar da Aeronáutica", "Base Aérea", "Vila Sobrinho (parte)"] },
  { regiao: "Centro", bairro: "Santa Fé (Parte Centro)", parcelamentos: ["Jardim Santa Fé", "West Park", "Vila Célia (parte)"] },
  { regiao: "Centro", bairro: "São Francisco", parcelamentos: ["Vila São Francisco", "Jardim Lara", "Monte Castelo (parte)", "Vila Integração"] },
  { regiao: "Imbirussu", bairro: "Nova Campo Grande", parcelamentos: ["Nova Campo Grande", "Jardim Iná", "Vila Serradinho", "Jardim Carioca"] },
  { regiao: "Imbirussu", bairro: "Núcleo Industrial", parcelamentos: ["Polo Empresarial de Campo Grande", "Indubrasil", "Residencial Nelson Trad"] },
  { regiao: "Imbirussu", bairro: "Panamá", parcelamentos: ["Jardim Panamá", "Residencial West Park", "Vila Alba", "Zé Pereira"] },
  { regiao: "Imbirussu", bairro: "Popular", parcelamentos: ["Vila Popular", "Jardim Sayonara", "Vila Zé Pereira (parte)", "Romano"] },
  { regiao: "Imbirussu", bairro: "Santo Amaro", parcelamentos: ["Vila Santo Amaro", "Vila Almeida", "Jardim Lara", "Santo Antônio (parte)"] },
  { regiao: "Imbirussu", bairro: "Santo Antônio", parcelamentos: ["Vila Santo Antônio", "Silvia Regina", "Jardim Imá", "Recanto dos Pássaros"] },
  { regiao: "Imbirussu", bairro: "Sobrinho", parcelamentos: ["Vila Sobrinho", "Zapran", "Vila Lara", "Jardim Palos Verdes"] },
  { regiao: "Lagoa", bairro: "Bandeirantes", parcelamentos: ["Vila Bandeirantes", "Nova Bandeirantes", "Vila Argolo"] },
  { regiao: "Lagoa", bairro: "Batistão", parcelamentos: ["Jardim Batistão", "Jardim São Conrado (parte)", "Tijuca (parte)"] },
  { regiao: "Lagoa", bairro: "Caiobá", parcelamentos: ["Portal Caiobá (I, II e III)", "Rancho Alegre", "Residencial Celina Jallad", "Vila Nova Jerusalém"] },
  { regiao: "Lagoa", bairro: "Coophavila II", parcelamentos: ["Conjunto Habitacional Coophavila II", "Jardim Tarumã (parte)", "Marambaia"] },
  { regiao: "Lagoa", bairro: "Guanandi", parcelamentos: ["Vila Guanandi", "Miramontes", "Vila Jacy (parte)", "Jardim Europa"] },
  { regiao: "Lagoa", bairro: "Leblon", parcelamentos: ["Vila Leblon", "Jardim Centenário (parte)", "Nova Guaporé"] },
  { regiao: "Lagoa", bairro: "São Conrado", parcelamentos: ["Jardim São Conrado", "Santa Emília", "Jardim Lara"] },
  { regiao: "Lagoa", bairro: "Tarumã", parcelamentos: ["Jardim Tarumã", "Coophavila (fração)", "Residencial Oliveira"] },
  { regiao: "Lagoa", bairro: "Taveirópolis", parcelamentos: ["Vila Taveirópolis", "Bela Vista", "Vila Nova Bandeirantes (parte)"] },
  { regiao: "Lagoa", bairro: "Tijuca", parcelamentos: ["Jardim Tijuca (I e II)", "São Conrado (parte)", "Conjunto Lagoa"] },
  { regiao: "Lagoa", bairro: "União", parcelamentos: ["Conjunto União", "Nascente do Segredo (parte)", "Vila Base"] },
  { regiao: "Prosa", bairro: "Autonomista", parcelamentos: ["Jardim Autonomista", "Vila Margarida (parte)", "Santa Fé (parte)"] },
  { regiao: "Prosa", bairro: "Carandá", parcelamentos: ["Carandá Bosque (I e II)", "Residencial Pousada do Pescador"] },
  { regiao: "Prosa", bairro: "Chácara Cachoeira", parcelamentos: ["Chácara Cachoeira", "Miguel Couto", "Residenciais do Bosque"] },
  { regiao: "Prosa", bairro: "Chácara dos Poderes", parcelamentos: ["Chácara dos Poderes", "Green Park"] },
  { regiao: "Prosa", bairro: "Estrela Dalva", parcelamentos: ["Jardim Estrela Dalva", "Tamandaré", "Novo Horizonte"] },
  { regiao: "Prosa", bairro: "Margarida", parcelamentos: ["Vila Margarida", "Giocondo Orsi", "Kaveira"] },
  { regiao: "Prosa", bairro: "Mata do Jacinto", parcelamentos: ["Conjunto Habitacional Mata do Jacinto", "Sóter", "Residencial Royal Park"] },
  { regiao: "Prosa", bairro: "Noroeste", parcelamentos: ["Jardim Noroeste", "Serraville", "Residencial Green Society"] },
  { regiao: "Prosa", bairro: "Novos Estados", parcelamentos: ["Jardim Novos Estados", "Parque Novos Estados", "Residencial Estrela Park"] },
  { regiao: "Prosa", bairro: "Santa Fé", parcelamentos: ["Santa Fé", "Vila Polon", "Altos da Afonso Pena"] },
  { regiao: "Prosa", bairro: "Veraneio", parcelamentos: ["Jardim Veraneio", "Parque dos Poderes (Setor Administrativo)", "Residencial Alphaville (I, II, III, IV)"] },
  { regiao: "Segredo", bairro: "Coronel Antonino", parcelamentos: ["Vila Coronel Antonino", "Estrela do Sul", "Vila Rica", "IPÊ"] },
  { regiao: "Segredo", bairro: "José Abrão", parcelamentos: ["Conjunto Habitacional José Abrão", "Santa Luzia", "Vila Lara"] },
  { regiao: "Segredo", bairro: "Mata do Segredo", parcelamentos: ["Mata do Segredo", "Jardim Presidente", "Residencial Parati (fração)", "Campo Belo"] },
  { regiao: "Segredo", bairro: "Monte Castelo", parcelamentos: ["Vila Monte Castelo", "Segredo", "Vila Nasser (parte)"] },
  { regiao: "Segredo", bairro: "Nasser", parcelamentos: ["Vila Nasser", "Jardim Paradiso", "Siriema", "Santa Carmen"] },
  { regiao: "Segredo", bairro: "Nova Lima", parcelamentos: ["Jardim Nova Lima", "Jardim Anache", "Jardim Columbia", "Jardim Campo Belo", "Tarsila do Amaral"] },
  { regiao: "Segredo", bairro: "Seminário", parcelamentos: ["Jardim Seminário", "Vila Marli", "Tamandaré", "Vila Dedé"] },
];

export const OUTDATED_BAIRROS = [
  "Amambaí", "Bandeira", "Bela Vista", "Jardim Veneza", "Coophavila", "Vila Nasser", "Jardim Leblon", "Jardim Seminário",
];
