/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProcessarRouteImport } from './routes/_app/processar'
import { Route as AppHistoricoRouteImport } from './routes/_app/historico'
import { Route as AppGeoRouteImport } from './routes/_app/geo'
import { Route as AppDicionarioRouteImport } from './routes/_app/dicionario'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppGeoIndexRouteImport } from './routes/_app/geo/index'
import { Route as AppGeoResultadoRouteImport } from './routes/_app/geo/resultado'
import { Route as AppGeoNormalizacaoRouteImport } from './routes/_app/geo/normalizacao'
import { Route as AppGeoImportarRouteImport } from './routes/_app/geo/importar'
import { Route as AppGeoExportacoesRouteImport } from './routes/_app/geo/exportacoes'
import { Route as AppGeoBaseRouteImport } from './routes/_app/geo/base'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProcessarRoute = AppProcessarRouteImport.update({
  id: '/processar',
  path: '/processar',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppGeoRoute = AppGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => AppRoute,
} as any)
const AppDicionarioRoute = AppDicionarioRouteImport.update({
  id: '/dicionario',
  path: '/dicionario',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppGeoIndexRoute = AppGeoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGeoRoute,
} as any)
const AppGeoResultadoRoute = AppGeoResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => AppGeoRoute,
} as any)
const AppGeoNormalizacaoRoute = AppGeoNormalizacaoRouteImport.update({
  id: '/normalizacao',
  path: '/normalizacao',
  getParentRoute: () => AppGeoRoute,
} as any)
const AppGeoImportarRoute = AppGeoImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AppGeoRoute,
} as any)
const AppGeoExportacoesRoute = AppGeoExportacoesRouteImport.update({
  id: '/exportacoes',
  path: '/exportacoes',
  getParentRoute: () => AppGeoRoute,
} as any)
const AppGeoBaseRoute = AppGeoBaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => AppGeoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dicionario': typeof AppDicionarioRoute
  '/geo': typeof AppGeoRouteWithChildren
  '/historico': typeof AppHistoricoRoute
  '/processar': typeof AppProcessarRoute
  '/geo/base': typeof AppGeoBaseRoute
  '/geo/exportacoes': typeof AppGeoExportacoesRoute
  '/geo/importar': typeof AppGeoImportarRoute
  '/geo/normalizacao': typeof AppGeoNormalizacaoRoute
  '/geo/resultado': typeof AppGeoResultadoRoute
  '/geo/': typeof AppGeoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dicionario': typeof AppDicionarioRoute
  '/historico': typeof AppHistoricoRoute
  '/processar': typeof AppProcessarRoute
  '/geo/base': typeof AppGeoBaseRoute
  '/geo/exportacoes': typeof AppGeoExportacoesRoute
  '/geo/importar': typeof AppGeoImportarRoute
  '/geo/normalizacao': typeof AppGeoNormalizacaoRoute
  '/geo/resultado': typeof AppGeoResultadoRoute
  '/geo': typeof AppGeoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dicionario': typeof AppDicionarioRoute
  '/_app/geo': typeof AppGeoRouteWithChildren
  '/_app/historico': typeof AppHistoricoRoute
  '/_app/processar': typeof AppProcessarRoute
  '/_app/geo/base': typeof AppGeoBaseRoute
  '/_app/geo/exportacoes': typeof AppGeoExportacoesRoute
  '/_app/geo/importar': typeof AppGeoImportarRoute
  '/_app/geo/normalizacao': typeof AppGeoNormalizacaoRoute
  '/_app/geo/resultado': typeof AppGeoResultadoRoute
  '/_app/geo/': typeof AppGeoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/dicionario'
    | '/geo'
    | '/historico'
    | '/processar'
    | '/geo/base'
    | '/geo/exportacoes'
    | '/geo/importar'
    | '/geo/normalizacao'
    | '/geo/resultado'
    | '/geo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/dicionario'
    | '/historico'
    | '/processar'
    | '/geo/base'
    | '/geo/exportacoes'
    | '/geo/importar'
    | '/geo/normalizacao'
    | '/geo/resultado'
    | '/geo'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/configuracoes'
    | '/_app/dicionario'
    | '/_app/geo'
    | '/_app/historico'
    | '/_app/processar'
    | '/_app/geo/base'
    | '/_app/geo/exportacoes'
    | '/_app/geo/importar'
    | '/_app/geo/normalizacao'
    | '/_app/geo/resultado'
    | '/_app/geo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/processar': {
      id: '/_app/processar'
      path: '/processar'
      fullPath: '/processar'
      preLoaderRoute: typeof AppProcessarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/geo': {
      id: '/_app/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof AppGeoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dicionario': {
      id: '/_app/dicionario'
      path: '/dicionario'
      fullPath: '/dicionario'
      preLoaderRoute: typeof AppDicionarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/geo/': {
      id: '/_app/geo/'
      path: '/'
      fullPath: '/geo/'
      preLoaderRoute: typeof AppGeoIndexRouteImport
      parentRoute: typeof AppGeoRoute
    }
    '/_app/geo/resultado': {
      id: '/_app/geo/resultado'
      path: '/resultado'
      fullPath: '/geo/resultado'
      preLoaderRoute: typeof AppGeoResultadoRouteImport
      parentRoute: typeof AppGeoRoute
    }
    '/_app/geo/normalizacao': {
      id: '/_app/geo/normalizacao'
      path: '/normalizacao'
      fullPath: '/geo/normalizacao'
      preLoaderRoute: typeof AppGeoNormalizacaoRouteImport
      parentRoute: typeof AppGeoRoute
    }
    '/_app/geo/importar': {
      id: '/_app/geo/importar'
      path: '/importar'
      fullPath: '/geo/importar'
      preLoaderRoute: typeof AppGeoImportarRouteImport
      parentRoute: typeof AppGeoRoute
    }
    '/_app/geo/exportacoes': {
      id: '/_app/geo/exportacoes'
      path: '/exportacoes'
      fullPath: '/geo/exportacoes'
      preLoaderRoute: typeof AppGeoExportacoesRouteImport
      parentRoute: typeof AppGeoRoute
    }
    '/_app/geo/base': {
      id: '/_app/geo/base'
      path: '/base'
      fullPath: '/geo/base'
      preLoaderRoute: typeof AppGeoBaseRouteImport
      parentRoute: typeof AppGeoRoute
    }
  }
}

interface AppGeoRouteChildren {
  AppGeoBaseRoute: typeof AppGeoBaseRoute
  AppGeoExportacoesRoute: typeof AppGeoExportacoesRoute
  AppGeoImportarRoute: typeof AppGeoImportarRoute
  AppGeoNormalizacaoRoute: typeof AppGeoNormalizacaoRoute
  AppGeoResultadoRoute: typeof AppGeoResultadoRoute
  AppGeoIndexRoute: typeof AppGeoIndexRoute
}

const AppGeoRouteChildren: AppGeoRouteChildren = {
  AppGeoBaseRoute: AppGeoBaseRoute,
  AppGeoExportacoesRoute: AppGeoExportacoesRoute,
  AppGeoImportarRoute: AppGeoImportarRoute,
  AppGeoNormalizacaoRoute: AppGeoNormalizacaoRoute,
  AppGeoResultadoRoute: AppGeoResultadoRoute,
  AppGeoIndexRoute: AppGeoIndexRoute,
}

const AppGeoRouteWithChildren =
  AppGeoRoute._addFileChildren(AppGeoRouteChildren)

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDicionarioRoute: typeof AppDicionarioRoute
  AppGeoRoute: typeof AppGeoRouteWithChildren
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppProcessarRoute: typeof AppProcessarRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDicionarioRoute: AppDicionarioRoute,
  AppGeoRoute: AppGeoRouteWithChildren,
  AppHistoricoRoute: AppHistoricoRoute,
  AppProcessarRoute: AppProcessarRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
