/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as DicionarioRouteImport } from './routes/dicionario'
import { Route as IndexRouteImport } from './routes/index'

const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const DicionarioRoute = DicionarioRouteImport.update({
  id: '/dicionario',
  path: '/dicionario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dicionario': typeof DicionarioRoute
  '/historico': typeof HistoricoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dicionario': typeof DicionarioRoute
  '/historico': typeof HistoricoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dicionario': typeof DicionarioRoute
  '/historico': typeof HistoricoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dicionario' | '/historico'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dicionario' | '/historico'
  id: '__root__' | '/' | '/dicionario' | '/historico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DicionarioRoute: typeof DicionarioRoute
  HistoricoRoute: typeof HistoricoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicionario': {
      id: '/dicionario'
      path: '/dicionario'
      fullPath: '/dicionario'
      preLoaderRoute: typeof DicionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DicionarioRoute: DicionarioRoute,
  HistoricoRoute: HistoricoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
